### ISSUE TITLE
Fill out page with survey details

### ISSUE THREAD

**Issue by mikejbrown** [amybrown42/amybrown42.github.io#1]
Do you (@amybrown42) want https://amybrown42.github.io to take people directly to the page about the survey, or we could have something like https://amybrown42.github.io/survey be the link you send out?

**Comment by amybrown42** [comment]
Hmmmm. Probs first? Maybe 2nd... i was thinking originally a "general"
homepage with a big survey button on it....

**Comment by mikejbrown** [comment]
> Hmmmm. Probs first? Maybe 2nd... i was thinking originally a "general" homepage with a big survey button on it....

I was just thinking that if you were going to use the site for other things as well, it would be cleaner to keep the survey on a separate page. Easy enough to change either way.

**Comment by mikejbrown** [comment]
@amybrown42 How about that? The styling can of course be changed fairly easily. Will want to check on phone/tablet as well.

**Comment by mikejbrown** [comment]
Resolved :tada:
