### ISSUE TITLE
Custom domain

### ISSUE THREAD

**Issue by mikejbrown** [amybrown42/amybrown42.github.io#2]
https://help.github.com/en/github/working-with-github-pages/about-custom-domains-and-github-pages
https://help.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site

- [x] Register custom domain(s)
- [x] Configure on github
- [x] Test routing works
- [x] Enforce HTTPS

**Comment by amybrown42** [comment]
- [x] Enforce HTTPS

**Comment by mikejbrown** [comment]
Resolved
